### ISSUE TITLE
How to Fix this

### ISSUE THREAD

**Issue by RavenIsh34** [fibelatti/photo-widget#24] opened 2024-01-21 18:30 UTC
![Screenshot_20240122_022717_ginlemon flowerfree](https://github.com/fibelatti/photo-widget/assets/107761586/fdb5c32d-411b-4b22-855d-96e41733e159)

You need to fix this, Landscape "Fix" i dont what to do
Huawei Y7a, Smart Launcher Use
Latest Material Widget use

**Comment by RavenIsh34** [comment] 2024-01-21 18:39
![Screenshot_20240122_023751_ginlemon flowerfree](https://github.com/fibelatti/photo-widget/assets/107761586/d02414e7-8d9f-4542-a1a4-3ef19988d2ce)

This is the main problem cuz 1X1 only show, but if you add portrait widget and landscape widget option it can be fixed

**Comment by fibelatti** [comment] 2024-01-21 19:06
Hi @RavenIsh34, thanks for bringing this to my attention. I'll investigate what the issue is with that custom launcher and work on a fix.

**Comment by RavenIsh34** [comment] 2024-01-21 19:19
Yoh thank you for response dev i really love this app 

Not working when i use this option
![Screenshot_20240122_031529_com fibelatti photowidget debug](https://github.com/fibelatti/photo-widget/assets/107761586/9be29692-e394-4614-a21e-ce22e09ca978)

But,

If i use this option, it will work
![Screenshot_20240122_023751_ginlemon flowerfree](https://github.com/fibelatti/photo-widget/assets/107761586/cd74db72-f619-46a4-9161-390539511c14)

**Comment by fibelatti** [comment] 2024-01-21 20:49
Thanks for using the app @RavenIsh34, I'm glad you like it. I'll need to find a workaround to make placing widgets from within the app work on any device brand / launcher. Unfortunately it's an Android API which doesn't work the same on all devices. Samsung devices had a similar problem which I fixed, so I should be able to find a solution for this problem as well, otherwise I'll make it possible to add all aspect ratios from the widget picker.

**Comment by fibelatti** [comment] 2024-01-24 22:24
Hi @RavenIsh34, I'm releasing an update in the next couple days which will allow you to change the aspect ratio of any widget. Here's a quick demo:

https://github.com/fibelatti/photo-widget/assets/3277516/939eb6ac-7d08-4ab6-b2f7-6c0f237b161e

**Comment by RavenIsh34** [comment] 2024-01-25 16:58
Hi, that nice i can't wait

**Comment by fibelatti** [comment] 2024-01-28 15:13
@RavenIsh34 version 1.2 is now available on the Play Store, so I'm closing this issue as resolved.

**Closed by fibelatti** 2024-01-28 15:13 UTC
Labels: bug
